# Provincial personal income tax
base_vec_tau_PIT:    [0.06, 0.075, 0.125, 0.15, 0.20]
variant_vec_tau_PIT:    [0.06, 0.075, 0.125, 0.15, 0.20]
base_vec_thr_lo_PIT: [0.0, 3.0, 4.5, 6.0, 8.0]
variant_vec_thr_lo_PIT: [0.0, 3.0, 4.5, 6.0, 8.0]
# Federal personal income tax
base_vec_tau_fed_PIT:    [0.06, 0.075, 0.125, 0.15, 0.20]
variant_vec_tau_fed_PIT:    [0.06, 0.075, 0.125, 0.15, 0.20]
base_vec_thr_lo_fed_PIT: [0.0, 3.0, 4.5, 6.0, 8.0]
variant_vec_thr_lo_fed_PIT: [0.0, 3.0, 4.5, 6.0, 8.0]
# Simulation parameters
T:  16
n_sims: 2
# for tax shock in v2_pit_rate_scenario:
shk_brkt: 3
shk_amt: 0.05